# Generated by Django 5.2 on 2025-04-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_patient", models.CharField(max_length=255)),
                ("value", models.IntegerField()),
                ("pred", models.CharField(max_length=10)),
                ("confidence", models.IntegerField()),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
